name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
        - 'v*'  # Trigger when a tag like v1.0.0 is pushed

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    
    - name: Extract version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        
    # TODO: Use environment variable for tagging purposes
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pet-store/data-transform:0.1.0
