name: Docker Image CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    tags:
      - 'v*'  # Trigger on tag push (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK (required for building Spring Boot app)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Updated distribution

      # Build 
      - name: Build
        run: ./gradlew clean build -x test
      
      # Test
      - name: Test
        run: ./gradlew clean test

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            petStore/data-transform:0.1.0  
            petStore/data-transform:latest  
