name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
        - 'v*'  # Trigger when a tag like v1.0.0 is pushed

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    
    - name: Extract version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
    # Set up Docker Buildx (optional but recommended for multi-platform support)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build and Push Docker Image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          petStore/data-transform:${{ env.VERSION }}
          petStore/data-transform:latest
